### ISSUE TITLE
I am a grandma, and I have been gaming longer that you've been alive, likely

### ISSUE THREAD

**Issue by shava23** [VojtaStruhar/steam-review-template#1]
Could you manage to use something other than "Grandma" for the last option?  Speaking as a woman in her 60s who's been gaming (miniatures, Avalon Hill Games, D&D 1st edition) since the 70s, it comes off as both sexist and ageist to me.  

Probably just kill it.  Maybe "Senile" or something?  I don't know.  But the fact is, some games are considered too advanced (or rough) for children.

**_No game is to advanced or rough for grandmothers per se._**  Remember, the first computer games were published for the public in the late 70s -- I was late teens/20s then.

You are perpetuating a toxic stereotype.  

Equally as many women are graduating MIT these days -- and for ages -- as men.  Many of them are already mothers.  Many will be grandmothers if they aren't already (I was part of the MIT community in the 70s and 80s).

We are not doormats, dumb, or computer illiterate, in general.  Any woman born in the 1960s was a teen when computer games first became popular, and is "grandma" age now.

![image](https://user-images.githubusercontent.com/92231669/143163033-3ee52a12-7fbb-4c8f-ad31-e279d34ae7d1.png)

Thanks for your consideration.

**Comment by instalab** [comment]
I agree. If you want to keep it @VojtaStruhar, maybe replace it with "Senior".

Although, I would argue that this last checkbox is not needed at all since Senior = Adult.
I would like to know what you meant when creating this checkbox.
What kind of games would qualify as "Grandma audience"?
Some people seem to think it's casual games.
However, I would like to point such people to the following report: https://www.datagenetics.com/blog/december12010
This article confirms that the medium age of casual gamers is 40 yo, which is an average medium human age! A broad spectrum of ages enjoys such games. As a result, classifying casual games as "Grandma" is both sexist and ageist.

**Comment by VojtaStruhar** [comment]
![offensive_funny_meme](https://user-images.githubusercontent.com/49688205/145275232-019732b2-63fa-4208-890a-71a8347878bb.jpg)

**Comment by VojtaStruhar** [comment]
@instalab @shava23 
![You found it offensive, I found it funny meme](https://user-images.githubusercontent.com/49688205/145275232-019732b2-63fa-4208-890a-71a8347878bb.jpg)

**Comment by shava23** [comment]
So, are you going to add a "puerile" category to cover people who give feedback like this to constructive criticism?

Sigh.

Also, thank you @instalab!

**Comment by VojtaStruhar** [comment]
This is not a constructive criticism. This is some social justice warrior bullying which I'm not going to conform to. Thanks for making my week though, we've been laughing at this issue with my friends and colleagues for good couple of days now 😄 

---

Since I'm making a proper response now, I might as well call some bs:

> I am a grandma, and I have been gaming longer that you've been alive, likely 

Why does that matter? Does it give you rights to decide how my jokes and my software should look like? Didn't think so.

> ...it comes off as both sexist and ageist to me.

You chose to be offended, [but that's on you](https://twitter.com/rickygervais/status/389014685808590849).

> No game is to advanced or rough for grandmothers per se. _(...)_ We are not doormats, dumb, or computer illiterate, in general.

Something like that actually never even crossed my mind. The _Grandma_ category actually seems like the most wholesome to me. I would say most games are not created with this specific playerbase in mind, but it is great when everyone is able to enjoy a game. Animal Crossing is [great example](https://www.nintendolife.com/news/2020/08/random_89-year-old_animal_crossing_grandma_is_back_with_her_new_horizons_island_tour) of this. That interview seems like a pure wholesomeness to me, no bad intentions in sight.

---

From what I can understand, you are not a typical grandma. Therefore don't be surprised that the category doesn't quite fit you. You are a very unique, very special snowflake ❄️❤️

**Comment by twome** [comment]
Vojtěch, you're a cretin with nothing useful to contribute to the world. This project is worse than useless and fills Steam with unreadable, useless spam reviews, and you are personally a vile, stupid piece of shit

**Comment by VojtaStruhar** [comment]
@twome Thank you for your kind words, brother.

**Comment by Justman100** [comment]
@VojtaStruhar

What was going on here?

**Comment by VojtaStruhar** [comment]
@Justman100  I wish I knew 😂

**Comment by fallguysbattlepass** [comment]
https://github.com/VojtaStruhar/steam-review-template/assets/166792504/48079f0a-4d42-4fe1-9df4-d4745b68c743

**Comment by avalonv** [comment]
Not only are you responsible for flooding steam with unhelpful reviews that convey precisely zero information about why a game is good, or even a baseline understanding of its technical details or how it performs, you manage to be extremely rude and aggressive to people still willing to give constructive feedback to your worthless "software". 

Get off your high horse. This program's contribution to the world is negative. Steam deliberately changed the way it filters reviews partly because of the prevalence of unhelpful reviews of the kind this project purports to help write. For people so lacking in creativity they have to fill a form to express why they liked something.

Some of us aren't offended, we just think you're being a dick for no reason.

**Comment by OsakaPhysics** [comment]
Crazy.

**Comment by MartinVonReichenberg** [comment]
¡Hooooooši,

tak toto je celé na „pěst ze střechy”!

**Comment by Ktosnapewno999** [comment]
@VojtaStruhar whatever you do every time there will be haters i think this project is really cool.

**Comment by MagicDippyEgg** [comment]
i feel like people care so much over small stuff
